In [6]:
# Step 1: Import Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import normalize
import scipy.sparse
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

# Step 2: Read data as array
iris = datasets.load_iris()
list(iris.keys())
X = iris["data"] # petal width

# Step 3: Normalize Data
X = normalize(X, norm='l2')

# Step 4: Split data into target and input
y = iris["target"]
m = y.shape[0]

# Step 5: Train Test Split
# Test Split
X_test = np.concatenate([X[40:50,:], X[90:100,:], X[140:150,:]])
y_test = np.concatenate([y[40:50], y[90:100], y[140:150]])
print("test input shape: ",X_test.shape,"test output shape: ", y_test.shape)
# Train Split
X = np.concatenate([X[0:40,:], X[50:90,:], X[100:140,:]])
y = np.concatenate([y[0:40], y[50:90], y[100:140]])
print("train input shape: ", X.shape,"train output shape: ", y.shape)

# Step 6: One-Hot Encoding
def oneHotIt(Y):
    m = Y.shape[0]
    OHX = scipy.sparse.csr_matrix((np.ones(m), (Y, np.array(range(m)))))
    OHX = np.array(OHX.todense()).T
    return OHX
y_mat = oneHotIt(y)  # Next we convert the integer class coding into a one-hot representation
yo=y_mat

# Step 7: Define number of iterations, learning rate, and iniital theta

iterations = [10, 100, 1000, 10000]

eta = 0.1 # learning rate
m = y.shape[0]
for n_iterations in iterations:
    theta = np.random.rand(4,3)  # reset theta for each iteration
    for iteration in range(n_iterations):
        logits = X.dot(theta)
        y_proba = softmax(logits, axis=1)
        error = y_proba - y_mat  # Use y_mat instead of y
        gradients = 1/m * X.T.dot(error)
        theta = theta - eta * gradients
    # Compute the cross-entropy loss
    logits = X.dot(theta)
    y_proba = softmax(logits, axis=1)
    cross_entropy = -np.mean(np.sum(y_mat * np.log(y_proba + 1e-7), axis=1))  # Use y_mat instead of y
    print("Cross-entropy loss after:", n_iterations, "iterations:", cross_entropy)

# Step 11: Test Accuracy (Combined)

from scipy.special import softmax
theta_best = theta
y_test_soft = X_test.dot(theta_best)
y_test_soft = softmax(y_test_soft, axis =0)
print(y_test_soft[:5,:])


y_test_soft = np.argmax(y_test_soft, axis = 1)

accuracy = np.sum(y_test == y_test_soft) / (float(len(y_test_soft)))

print("\n Testing Accuracy after",n_iterations,"iterations:\n", accuracy*100)

# Test Accuracy (class-wise)

cm = y_test == y_test_soft

c1 = np.sum(cm[:10])/float(10)
c2 = np.sum(cm[10:20])/float(10)
c3 = np.sum(cm[20:])/float(10)
print("Class-1 Accuracy: ", c1*100,"\nClass-1 Accuracy: ", c2*100,"\nClass-1 Accuracy: ", c3*100)

test input shape:  (30, 4) test output shape:  (30,)
train input shape:  (120, 4) train output shape:  (120,)
Cross-entropy loss after: 10 iterations: 1.0486170566460653
Cross-entropy loss after: 100 iterations: 1.0324314913767128
Cross-entropy loss after: 1000 iterations: 0.5950138392122908
Cross-entropy loss after: 10000 iterations: 0.31618791255362805
[[1.47779737e-01 2.17860614e-02 6.43482016e-05]
 [4.42382670e-02 3.41319105e-02 1.39754155e-04]
 [1.27412194e-01 2.15301684e-02 7.79028776e-05]
 [6.81700835e-02 2.18118612e-02 1.63396197e-04]
 [6.14626270e-02 2.15770799e-02 1.85567714e-04]]

 Testing Accuracy after 10000 iterations:
 100.0
Class-1 Accuracy:  100.0 
Class-1 Accuracy:  100.0 
Class-1 Accuracy:  100.0
