Date : 6th Nov 2023

Step 1: Import Libraries

In [3]:
import pandas as pd;
import numpy as np

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import normalize
import scipy.sparse
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

Step 2: Read data as array

In [4]:
iris = datasets.load_iris()
list(iris.keys())
X = iris["data"] # petal width

Step 3: Normalize data

In [5]:
X = normalize(X, norm= 'l2')

Step 4: Split data into target and input

In [6]:
y = iris["target"]
m= y.shape[0]

Step 5: Train test split

In [7]:
# Test Split
X_test = np.concatenate([X[40:50,:],X[90:100,:],X[140:150,:]])
y_test = np.concatenate([y[40:50],y[90:100],y[140:150]])
print("test input shape: ",X_test.shape,"test output shape: ", y_test.shape)
# Train Split
X = np.concatenate([X[0:40,:], X[50:90,:], X[100:140,:]])
y = np.concatenate([y[0:40], y[50:90], y[100:140]])
print("train input shape: ", X.shape,"train output shape: ", y.shape)

test input shape:  (30, 4) test output shape:  (30,)
train input shape:  (120, 4) train output shape:  (120,)


Step 6: one-hot encoding

In [8]:
def oneHotIt(Y):
    m = Y.shape[0]
    OHX = scipy.sparse.csr_matrix((np.ones(m), (Y, np.array(range(m)))))
    OHX = np.array(OHX.todense()).T
    return OHX
y_mat = oneHotIt(y)  # Next we convert the integer class coding into a one-hot representation
yo=y_mat

Step 7: Define number of iterations, learning rate, and initial theta

In [9]:
n_iterations = 100

eta = 0.1 # learning rate
m = y.shape[0]
theta = np.random.rand(4,3)

Step 8: Run Gradient Descent (GD)

$step 1: s = X^T.\theta $

$step 2: H_\theta = \frac{1}{1+e^{-s}}$

$step 4:  e = H_\theta - y$

$step 5: \nabla = \frac{2}{m}X^T.e$

$step 6: \theta = \theta - \eta \nabla$

$ MSE = E[e^2]$


Step 9: Predict

In [10]:
from scipy.special import softmax
theta_best = theta
y_pred_soft = X.dot(theta_best)
y_pred_soft = softmax(y_pred_soft, axis =0)
print(y_pred_soft[:5,:])
y_pred_soft.shape

[[0.00808087 0.00663646 0.00908   ]
 [0.00809887 0.00682123 0.00897647]
 [0.00808919 0.00667022 0.00907774]
 [0.00808755 0.00682131 0.009002  ]
 [0.00807469 0.00658879 0.00910831]]


(120, 3)

In [11]:
y_train_pred = np.argmax(y_pred_soft, axis = 1)

Step 10: Train accuracy (combined)

In [12]:
accuracy = np.sum(y_train_pred == y) / (float(len(y)))
print("\n Training Accuracy after",n_iterations,"iterations:\n", accuracy*100)


 Training Accuracy after 100 iterations:
 33.33333333333333


Step 11: Test accuray (combined)

In [13]:
from scipy.special import softmax
theta_best = theta
y_test_soft = X_test.dot(theta_best)
y_test_soft = softmax(y_test_soft, axis =0)
print(y_test_soft[:5,:])

[[0.03238862 0.02653541 0.03635599]
 [0.0326032  0.02850611 0.03517619]
 [0.03222467 0.02640651 0.03617214]
 [0.0328791  0.02840802 0.03642529]
 [0.03245012 0.02768792 0.03601361]]


In [14]:
y_test_soft = np.argmax(y_test_soft, axis = 1)

accuracy = np.sum(y_test == y_test_soft) / (float(len(y_test_soft)))

print("\n Testing Accuracy after",n_iterations,"iterations:\n", accuracy*100)


 Testing Accuracy after 100 iterations:
 33.33333333333333


Test accuracy (class-wise)

In [16]:
cm = y_test == y_test_soft

c1 = np.sum(cm[:10])/float(10)
c2 = np.sum(cm[10:20])/float(10)
c3 = np.sum(cm[20:])/float(10)
print("Class-1 Accuracy: ", c1*100,"\nClass-1 Accuracy: ", c2*100,"\nClass-1 Accuracy: ", c3*100)

Class-1 Accuracy:  0.0 
Class-1 Accuracy:  100.0 
Class-1 Accuracy:  0.0
